
version: 2.1

orbs:
  android: circleci/android@2.0.0
  
executors:
    android-executor:
        docker:
            - image: circleci/android:api-30
        resource_class: medium

commands:
  restore_gradle:
    steps:
      - run:
          command: |
            find . -name 'build.gradle' | sort | xargs cat |
            shasum | awk '{print $1}' > ./tmp_gradle_cache_seed
          name: Generate cache checksum
      - restore_cache:
          key: gradle-v1a-{{ arch }}-{{ checksum "./tmp_gradle_cache_seed" }}
          name: Restore gradle cache
      - restore_cache:
          name: Restore gradle properties
          key: gradle-properties-${CIRCLE_WORKFLOW_ID}_21
      - restore_cache:
          name: Restore secret key ring
          key: secret-keys-${CIRCLE_WORKFLOW_ID}_21
  save_gradle:
    steps:
      - save_cache:
          name: Save gradle cache
          key: gradle-v1a-{{ arch }}-{{ checksum "./tmp_gradle_cache_seed" }}
          paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
      - save_cache:
          key: gradle-properties-${CIRCLE_WORKFLOW_ID}_21
          name: Save gradle properties
          paths:
            - ~/.gradle/gradle.properties
      - save_cache:
          key: secret-keys-${CIRCLE_WORKFLOW_ID}_21
          name: Save secret keys
          paths:
            - circularseekbar/secret-keys.gpg
  fetch_gradle_properties:
    steps:
      - run:
          name: Fetch gradle properties
          command: |
            mkdir -p ~/.gradle
            curl -L -o ~/.gradle/gradle.properties "https://drive.google.com/uc?export=download&id=$GRADLE_PROPERTY_PATH_FIELD_ID"
            curl -L -o circularseekbar/secret-keys.gpg "https://drive.google.com/uc?export=download&id=$SECRET_KEY_RING_PATH_FIELD_ID"
  
  
jobs:
  build:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android-executor
    working_directory: ~/code

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - restore_gradle
      - fetch_gradle_properties

      - run:
          name: find gradle properties
          command: find ~ -name "*.properties"

      # And finally run the release build
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - save_gradle
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: apk
      - run:
          name: Make App Bundle
          command: ./gradlew bundleRelease
      - store_artifacts:
          path: app/build/outputs/bundle/release
          destination: bundle
      - store_artifacts:
          path: app/build/outputs/mapping/release
          destination: mapping
      - persist_to_workspace:
          root: .
          paths:
          - .
  deploy:
    executor:
      name: android-executor
    steps:
      - attach_workspace:
          at: .
      - restore_gradle
      - fetch_gradle_properties
      - run:
          name: Upload to Maven Central
          command: ./gradlew publish

workflows:
  version: 2
  build_deploy:
    jobs:
    - build
    - deploy:
        requires:
          - build
        filters:
          branches:
            only:
              - master
              - /release\/.*/
